/**
 * Audit action types for logging
 */
export enum AuditAction {
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  PERMISSION_GRANT = 'PERMISSION_GRANT',
  PERMISSION_REVOKE = 'PERMISSION_REVOKE',
  SCOPE_CHANGE = 'SCOPE_CHANGE',
  RULE_EVALUATION = 'RULE_EVALUATION',
  APPROVAL_REQUEST = 'APPROVAL_REQUEST',
  APPROVAL_GRANT = 'APPROVAL_GRANT',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  ACCESS_DENIED = 'ACCESS_DENIED',
}
